### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by InsipidLake** [rocktimsaikia/animechan#89]
Is the API working as of 2024 Jan? I've been trying but API response returns null or keeps trying. Or just returns this
![image](https://github.com/rocktimsaikia/animechan/assets/155420059/6bbee43f-b602-49ab-b78e-4361e94ae76d)

**Comment by rocktimsaikia** [comment]
The backend port was failing for reason reason. I've restarted it, should be fine now. Currently busy atm but I will look into the logs later to debug what went wrong.

**Comment by ducgao** [comment]
The API return 500 internal server error.
Please help!

**Comment by rocktimsaikia** [comment]
should be fixed now.
