### ISSUE TITLE
Internal server error response from api

### ISSUE THREAD

**Issue by melosh101** [rocktimsaikia/animechan#97]
There currently seems to be an issue with the backend after the migration, I will into it as soon as I get a hold of the logs so I can try to reproduce

**Comment by rocktimsaikia** [comment]
I will look into this today later on. Same error as before. This is not because of db connectivity issues rather socket timeout issues that needs to be handled gracefully in server side.

**Comment by melosh101** [comment]
in general we need a to implement graceful handeling of errors on the backend instead of crashes

**Comment by rocktimsaikia** [comment]
All of the controllers are properly being handled for crashes like before in one of my latest commits. Should not happen again! Closing it for now. Lets see if that occurs again.
